name: flutter_cached_transition
description: "This package provides customizable widgets that preserve widget state while applying transition animations."
version: 1.0.2
publisher: ttankkeo112@gmail.com
repository: https://github.com/MTtankkeo/flutter_cached_transition

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
